#!/usr/bin/env bash
# Materialise .env.prod (gitignored) from the credentials Vercel pulled, then
# install the 5-minute market keeper in the VPS crontab.
set -euo pipefail
cd /root/pumpclip

POOLED="$(grep -m1 '^DATABASE_URL=' .env.local | cut -d= -f2- | tr -d '"')"
DIRECT="$(grep -m1 '^DATABASE_URL_UNPOOLED=' .env.local | cut -d= -f2- | tr -d '"')"

if [[ -z "$POOLED" || -z "$DIRECT" ]]; then
  echo "ERROR: could not read DATABASE_URL / DATABASE_URL_UNPOOLED from .env.local" >&2
  exit 1
fi

# Must be ignored, or the production password lands in a public repo.
if ! git check-ignore -q .env.prod; then
  echo "ERROR: .env.prod is NOT gitignored — refusing to write it." >&2
  exit 1
fi

umask 077
{
  echo "# Production Neon, generated by scripts/install-keeper.sh. Do not commit."
  echo "DATABASE_URL=\"$POOLED\""
  echo "DIRECT_URL=\"$DIRECT\""
} > .env.prod
chmod 600 .env.prod
echo "wrote .env.prod (mode 600, gitignored)"

LINE='*/5 * * * * /root/pumpclip/scripts/sync-cron.sh >> /var/log/pumpclip-sync.log 2>&1'
if crontab -l 2>/dev/null | grep -qF 'sync-cron.sh'; then
  echo "keeper already installed"
else
  { crontab -l 2>/dev/null || true; echo "$LINE"; } | crontab -
  echo "installed keeper: $LINE"
fi

crontab -l 2>/dev/null | grep -F 'sync-cron.sh' || true
